export const Users = [
    {
        id: 1,
        profilePicture: "profile/profile-1.jpg",
        username: "Manny dave",
    },
    {
        id: 2,
        profilePicture: "profile/profile-2.jpg",
        username: "emeka ebunike",
    },
    {
        id: 3,
        profilePicture: "profile/profile-3.jpg",
        username: "sholanke oloto",
    },
    {
        id: 4,
        profilePicture: "profile/profile-4.jpg",
        username: "agatha moore",
    },
    {
        id: 5,
        profilePicture: "profile/profile-4.jpg",
        username: "seyi makinde",
    },
    {
        id: 6,
        profilePicture: "profile/profile-4.jpg",
        username: "jeny lia",
    },
    {
        id: 7,
        profilePicture: "profile/profile-4.jpg",
        username: "enoge mazi",
    },
    {
        id: 8,
        profilePicture: "profile/profile-4.jpg",
        username: "pastor jeff",
    },
    {
        id: 9,
        profilePicture: "profile/profile-4.jpg",
        username: "amaka jones",
    },
    {
        id: 10,
        profilePicture: "profile/profile-4.jpg",
        username: "alaba oki",
    },
];

export const Posts = [
    {
        id: 1,
        desc: "this is my first post",
        photo: "posts/post-1.jpg",
        date: "5 mins ago",
        userId: 1,
        like: 1,
        credit: 300,
        comment: 9,
    },
    {
        id: 2,
        desc: "this is a second post",
        photo: "posts/post-2.jpg",
        date: "15 mins ago",
        userId: 2,
        like: 15,
        credit: 50,
        comment: 23,
    },
    {
        id: 3,
        desc: "this is the third post",
        photo: "posts/post-3.jpg",
        date: "1 mins ago",
        userId: 3,
        like: 10,
        credit: 370,
        comment: 6,
    },
    {
        id: 4,
        desc: "this is the fourth post",
        photo: "posts/post-4.jpg",
        date: "12 mins ago",
        userId: 4,
        like: 6,
        credit: 450,
        comment: 6,
    },
    {
        id: 4,
        desc: "this is the fourth post",
        photo: "posts/post-4.jpg",
        date: "12 mins ago",
        userId: 5,
        like: 6,
        credit: 450,
        comment: 6,
    },
    {
        id: 5,
        desc: "this is the fourth post",
        photo: "posts/post-4.jpg",
        date: "12 mins ago",
        userId: 6,
        like: 6,
        credit: 450,
        comment: 6,
    },
    {
        id: 6,
        desc: "this is the fourth post",
        photo: "posts/post-4.jpg",
        date: "12 mins ago",
        userId: 7,
        like: 6,
        credit: 450,
        comment: 6,
    },
    {
        id: 7,
        desc: "this is the fourth post",
        photo: "posts/post-4.jpg",
        date: "12 mins ago",
        userId: 8,
        like: 6,
        credit: 450,
        comment: 6,
    },
    {
        id: 8,
        desc: "this is the fourth post",
        photo: "posts/post-4.jpg",
        date: "12 mins ago",
        userId: 9,
        like: 6,
        credit: 450,
        comment: 6,
    },
    {
        id: 9,
        desc: "this is the fourth post",
        photo: "posts/post-4.jpg",
        date: "12 mins ago",
        userId: 10,
        like: 6,
        credit: 450,
        comment: 6,
    },
    
]
